### ISSUE TITLE
ntdll_RtlGetCurrentUmsThread_stub patch updates and issues with FC New Dawn CODEX Crack

### ISSUE THREAD

**Issue by Souravgoswami** [shefben/wine-patches#1]
Sorry I'm creating an issue here. But I too, find that the CODEX's Denuvo bypass for FastCry New Dawn doesn't work on WINE.

The existing patch on your repo should have fixed it, but it needs some updates. The header files have changed a little bit, so I've fixed them and compiled. But the compilation fails on WINE 9.22 on Archlinux:

```
  dlls/kernel32/x86_64-windows/libkernel32.a dlls/ntdll/x86_64-windows/libntdll.a -Wl,-O2 -Wl,--strip-all
collect2: error: ld returned 1 exit status
tools/winegcc/winegcc -o dlls/oleaut32/x86_64-windows/oleaut32.dll --wine-objdir . -b x86_64-w64-mingw32 -Wl,--wine-builtin -shared \
  ../wine/dlls/oleaut32/oleaut32.spec dlls/oleaut32/x86_64-windows/connpt.o \
  dlls/oleaut32/x86_64-windows/dispatch.o dlls/oleaut32/x86_64-windows/hash.o \
  dlls/oleaut32/x86_64-windows/oleaut.o dlls/oleaut32/x86_64-windows/olefont.o \
  dlls/oleaut32/x86_64-windows/olepicture.o dlls/oleaut32/x86_64-windows/olepropframe.o \
  dlls/oleaut32/x86_64-windows/recinfo.o dlls/oleaut32/x86_64-windows/safearray.o \
  dlls/oleaut32/x86_64-windows/thunks.o dlls/oleaut32/x86_64-windows/typelib.o \
  dlls/oleaut32/x86_64-windows/usrmarshal.o dlls/oleaut32/x86_64-windows/varformat.o \
  dlls/oleaut32/x86_64-windows/variant.o dlls/oleaut32/x86_64-windows/vartype.o \
  dlls/oleaut32/x86_64-windows/oleaut32_oaidl_p.o dlls/oleaut32/x86_64-windows/dlldata.o \
  dlls/oleaut32/x86_64-windows/oleaut32_ocidl_p.o dlls/oleaut32/oleaut32.res \
  dlls/oleaut32/x86_64-windows/oleaut32_oaidl_r.res \
  dlls/oleaut32/x86_64-windows/oleaut32_ocidl_r.res libs/uuid/x86_64-windows/libuuid.a \
  dlls/ole32/x86_64-windows/libole32.a dlls/rpcrt4/x86_64-windows/librpcrt4.a \
  dlls/user32/x86_64-windows/libuser32.a dlls/gdi32/x86_64-windows/libgdi32.a \
  dlls/advapi32/x86_64-windows/libadvapi32.a dlls/comctl32/x86_64-windows/libcomctl32.delay.a \
  dlls/urlmon/x86_64-windows/liburlmon.delay.a \
  dlls/windowscodecs/x86_64-windows/libwindowscodecs.delay.a \
  dlls/winecrt0/x86_64-windows/libwinecrt0.a dlls/ucrtbase/x86_64-windows/libucrtbase.a \
  dlls/kernel32/x86_64-windows/libkernel32.a dlls/ntdll/x86_64-windows/libntdll.a -Wl,-O2 -Wl,--strip-all
winegcc: /usr/bin/x86_64-w64-mingw32-gcc failed
make: *** [Makefile:137539: dlls/ntdll/x86_64-windows/ntdll.dll] Error 2
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...
```

Compiling just the ntdll.dll:

```
$ make dlls/ntdll/x86_64-windows/ntdll.dll V=1
tools/winegcc/winegcc -o dlls/ntdll/x86_64-windows/ntdll.dll --wine-objdir . -b x86_64-w64-mingw32 -Wl,--wine-builtin -shared \
  ../wine/dlls/ntdll/ntdll.spec -nodefaultlibs -Wl,--image-base,0x170000000 \
  dlls/ntdll/x86_64-windows/actctx.o dlls/ntdll/x86_64-windows/atom.o \
  dlls/ntdll/x86_64-windows/crypt.o dlls/ntdll/x86_64-windows/debugbuffer.o \
  dlls/ntdll/x86_64-windows/env.o dlls/ntdll/x86_64-windows/error.o \
  dlls/ntdll/x86_64-windows/exception.o dlls/ntdll/x86_64-windows/handletable.o \
  dlls/ntdll/x86_64-windows/heap.o dlls/ntdll/x86_64-windows/large_int.o \
  dlls/ntdll/x86_64-windows/loader.o dlls/ntdll/x86_64-windows/locale.o \
  dlls/ntdll/x86_64-windows/math.o dlls/ntdll/x86_64-windows/misc.o dlls/ntdll/x86_64-windows/path.o \
  dlls/ntdll/x86_64-windows/printf.o dlls/ntdll/x86_64-windows/process.o \
  dlls/ntdll/x86_64-windows/reg.o dlls/ntdll/x86_64-windows/relay.o \
  dlls/ntdll/x86_64-windows/resource.o dlls/ntdll/x86_64-windows/rtl.o \
  dlls/ntdll/x86_64-windows/rtlbitmap.o dlls/ntdll/x86_64-windows/rtlstr.o \
  dlls/ntdll/x86_64-windows/sec.o dlls/ntdll/x86_64-windows/signal_arm.o \
  dlls/ntdll/x86_64-windows/signal_arm64.o dlls/ntdll/x86_64-windows/signal_arm64ec.o \
  dlls/ntdll/x86_64-windows/signal_i386.o dlls/ntdll/x86_64-windows/signal_x86_64.o \
  dlls/ntdll/x86_64-windows/string.o dlls/ntdll/x86_64-windows/sync.o \
  dlls/ntdll/x86_64-windows/thread.o dlls/ntdll/x86_64-windows/threadpool.o \
  dlls/ntdll/x86_64-windows/time.o dlls/ntdll/x86_64-windows/unwind.o \
  dlls/ntdll/x86_64-windows/version.o dlls/ntdll/x86_64-windows/wcstring.o dlls/ntdll/version.res \
  libs/musl/x86_64-windows/libmusl.a dlls/winecrt0/x86_64-windows/libwinecrt0.a -Wl,-O2 -Wl,--strip-all
/usr/lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld: tmp6779536e/ntdll-00000000.spec.o:fake:(.edata+0xed0): undefined reference to `RtlGetCurrentUmsThread'
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/x86_64-w64-mingw32-gcc failed
make: *** [Makefile:137539: dlls/ntdll/x86_64-windows/ntdll.dll] Error 2
```

It's because the patch file won't work with latest 9.22 version of WINE.

Here's the updated patch file that compiles successfully:

````
--- a/dlls/ntdll/rtl.c
+++ b/dlls/ntdll/rtl.c
@@ -30,6 +30,7 @@
 #include "windef.h"
 #include "winbase.h"
 #include "winternl.h"
+#include "winnt.h"
 #include "ntuser.h"
 #include "wine/debug.h"
 #include "wine/exception.h"
@@ -1089,6 +1090,34 @@
 }

 /*********************************************************************
+ *           RtlGetCurrentUmsThread [NTDLL.@]
+ */
+DEFINE_FASTCALL_WRAPPER(RtlGetCurrentUmsThread, 16)
+LONG64 FASTCALL RtlGetCurrentUmsThread(struct _TEB *currentTEB)
+{
+    struct _TEB *TEB1;
+    struct _TEB *TEB2;
+
+    if (!currentTEB)
+        return STATUS_INVALID_PARAMETER;
+
+    TEB1 = (struct _TEB *)NtCurrentTeb();
+    TEB2 = TEB1->TlsSlots[4];
+
+    if (!TEB2)
+        return STATUS_NOT_SUPPORTED;
+
+    if (*(struct _TEB **)&TEB2->GdiTebBatch.Buffer[120] == TEB1)
+    {
+        /* *thread = **TEB2; */
+        currentTEB->Tib.ExceptionList = (struct _EXCEPTION_REGISTRATION_RECORD *)TEB2;
+        return STATUS_SUCCESS;
+    }
+
+    return STATUS_NOT_SUPPORTED;
+}
+
+/*********************************************************************
  *           RtlGetDeviceFamilyInfoEnum [NTDLL.@]
  */
 void WINAPI RtlGetDeviceFamilyInfoEnum(ULONGLONG *version, DWORD *family, DWORD *form)
diff --git a/dlls/ntdll/ntdll.spec b/dlls/ntdll/ntdll.spec
index dcfa30f356b..ae4deef854e 100755
--- a/dlls/ntdll/ntdll.spec
+++ b/dlls/ntdll/ntdll.spec
@@ -1113,6 +1113,7 @@
 @ stdcall RtlxOemStringToUnicodeSize(ptr) RtlOemStringToUnicodeSize
 @ stdcall RtlxUnicodeStringToAnsiSize(ptr) RtlUnicodeStringToAnsiSize
 @ stdcall RtlxUnicodeStringToOemSize(ptr) RtlUnicodeStringToOemSize
+@ stdcall -fastcall -arch=win64 RtlGetCurrentUmsThread(ptr)
 @ stdcall TpAllocCleanupGroup(ptr)
 @ stdcall TpAllocIoCompletion(ptr ptr ptr ptr ptr)
 @ stdcall TpAllocPool(ptr ptr)
``````````````````````````````````````````````````````````````````````````````

With this, WINE is compiled, but FC New Dawn launches the loading screen and exits:

```
$ WINEDEBUG=+loaddll,+vulkan wine FarCryNewDawn.exe
...
...
...
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkCmdBeginTransformFeedbackEXT"
0124:trace:vulkan:wine_vk_get_device_proc_addr Found name="vkCmdBeginTransformFeedbackEXT" in device table
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkCmdEndTransformFeedbackEXT"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkCmdEndTransformFeedbackEXT"
0124:trace:vulkan:wine_vk_get_device_proc_addr Found name="vkCmdEndTransformFeedbackEXT" in device table
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkCmdDrawIndirectByteCountEXT"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkCmdDrawIndirectByteCountEXT"
0124:trace:vulkan:wine_vk_get_device_proc_addr Found name="vkCmdDrawIndirectByteCountEXT" in device table
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkCmdBeginQueryIndexedEXT"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkCmdBeginQueryIndexedEXT"
0124:trace:vulkan:wine_vk_get_device_proc_addr Found name="vkCmdBeginQueryIndexedEXT" in device table
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkCmdEndQueryIndexedEXT"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkCmdEndQueryIndexedEXT"
0124:trace:vulkan:wine_vk_get_device_proc_addr Found name="vkCmdEndQueryIndexedEXT" in device table
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkGetImageViewHandleNVX"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkGetImageViewHandleNVX"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "vkGetImageViewHandleNVX".
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkGetImageViewAddressNVX"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkGetImageViewAddressNVX"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "vkGetImageViewAddressNVX".
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkCreateCuModuleNVX"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkCreateCuModuleNVX"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "vkCreateCuModuleNVX".
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkCreateCuFunctionNVX"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkCreateCuFunctionNVX"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "vkCreateCuFunctionNVX".
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkDestroyCuModuleNVX"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkDestroyCuModuleNVX"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "vkDestroyCuModuleNVX".
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkDestroyCuFunctionNVX"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkDestroyCuFunctionNVX"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "vkDestroyCuFunctionNVX".
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkCmdCuLaunchKernelNVX"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkCmdCuLaunchKernelNVX"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "vkCmdCuLaunchKernelNVX".
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkGetMemoryWin32HandleKHR"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkGetMemoryWin32HandleKHR"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "vkGetMemoryWin32HandleKHR".
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkGetMemoryWin32HandlePropertiesKHR"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkGetMemoryWin32HandlePropertiesKHR"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "vkGetMemoryWin32HandlePropertiesKHR".
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkGetSemaphoreWin32HandleKHR"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkGetSemaphoreWin32HandleKHR"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "vkGetSemaphoreWin32HandleKHR".
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkImportSemaphoreWin32HandleKHR"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkImportSemaphoreWin32HandleKHR"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "vkImportSemaphoreWin32HandleKHR".
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkCmdBindIndexBuffer2KHR"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkCmdBindIndexBuffer2KHR"
0124:trace:vulkan:wine_vk_get_device_proc_addr Found name="vkCmdBindIndexBuffer2KHR" in device table
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkGetRenderingAreaGranularityKHR"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkGetRenderingAreaGranularityKHR"
0124:trace:vulkan:wine_vk_get_device_proc_addr Found name="vkGetRenderingAreaGranularityKHR" in device table
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkGetDeviceImageSubresourceLayoutKHR"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkGetDeviceImageSubresourceLayoutKHR"
0124:trace:vulkan:wine_vk_get_device_proc_addr Found name="vkGetDeviceImageSubresourceLayoutKHR" in device table
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkGetImageSubresourceLayout2KHR"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkGetImageSubresourceLayout2KHR"
0124:trace:vulkan:wine_vk_get_device_proc_addr Found name="vkGetImageSubresourceLayout2KHR" in device table
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "vkWaitForPresentKHR"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "vkWaitForPresentKHR"
0124:trace:vulkan:wine_vk_get_device_proc_addr Found name="vkWaitForPresentKHR" in device table
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "wine_vkAcquireKeyedMutex"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "wine_vkAcquireKeyedMutex"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "wine_vkAcquireKeyedMutex".
0124:trace:vulkan:vkGetDeviceProcAddr 00000000003310F0, "wine_vkReleaseKeyedMutex"
0124:trace:vulkan:win32u_vkGetDeviceProcAddr device 0x5555853eef00, name "wine_vkReleaseKeyedMutex"
0124:warn:vulkan:vkGetDeviceProcAddr Unsupported device function: "wine_vkReleaseKeyedMutex".
0124:trace:vulkan:thunk64_vkGetDeviceQueue 0x3310f0, 0, 0, 0x11dc30
0124:trace:vulkan:thunk64_vkGetDeviceQueue 0x3310f0, 0, 0, 0x11dc40
0124:trace:vulkan:thunk64_vkGetDeviceQueue 0x3310f0, 0, 0, 0x11dcd0
0124:trace:vulkan:thunk64_vkGetPhysicalDeviceMemoryProperties 0x2f75b8, 0x122f290
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d6c0, 0x11d7b0
0124:trace:vulkan:thunk64_vkGetDeviceImageMemoryRequirements 0x3310f0, 0x11d6c0, 0x11d7b0
info:  Memory type mask for sparse resources: 0x7
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
0124:trace:vulkan:thunk64_vkGetDeviceBufferMemoryRequirements 0x3310f0, 0x11d980, 0x11d9e0
warn:  DXVK: No state cache file found
info:  DXVK: Graphics pipeline libraries supported
0124:trace:vulkan:thunk64_vkCreateDescriptorSetLayout 0x3310f0, 0x11d1c0, (nil), 0x123b9c8
0124:trace:vulkan:thunk64_vkCreatePipelineLayout 0x3310f0, 0x11d340, (nil), 0x1231268
0124:trace:vulkan:thunk64_vkGetShaderModuleCreateInfoIdentifierEXT 0x3310f0, 0x11d2f0, 0x1231460
0124:trace:vulkan:thunk64_vkCreateGraphicsPipelines 0x3310f0, 0x0, 1, 0x11d0b0, (nil), 0x11cf38
Unable to read VR Path Registry from C:\users\sourav\AppData\Local\openvr\openvrpaths.vrpath
0124:trace:vulkan:DllMain 00006FFFFCA20000, 0, 0000000000000001
011c:fixme:ver:GetCurrentPackageId (00007FFFFE2FFEB0 0000000000000000): stub

```

IDK for now but it seems not related to the patch. Without the patch, the loader screen doesn't load, with the patch at least that thing loads.
